### ISSUE TITLE
Loading Cycles in old Blender version crashes with this addon

### ISSUE THREAD

**Issue by fabiangeisler** [friedererdmann/blender_studio_scripts#4]
First of all: Thanks for this addon! It really does make my life easier with Blender.

I am running into an issue with Blender 2.92.0 (I know its super old and we want to get rid of it hopefully soon). The patched function in this line includes an asterix which enforces the following arguments to be keyword only arguments:
https://github.com/friedererdmann/blender_studio_scripts/blob/95759cafba871bb2589c959608561bc6afddbcbf/startup/__BLENDER_STUDIO_SCRIPTS__.py#L38C40-L38C43
This is an issue when loading Cycles for that Blender version and also results in an empty Addons section in the preferences. Removing it resolves the issue and I am wondering if there is a good reason to have it in there?

**Comment by fabiangeisler** [comment]
This is the (slightly modified) error message I get:
```
Exception in module register(): [...]/Blender/blender-2.92.0-linux-x64/2.92/scripts/addons/cycles/__init__.py
Traceback (most recent call last):
  File "[...]/Blender/blender-2.92.0-linux-x64/2.92/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "[...]/Blender/blender-2.92.0-linux-x64/2.92/scripts/addons/cycles/__init__.py", line 132, in register
    engine.init()
  File "[...]/Blender/blender-2.92.0-linux-x64/2.92/scripts/addons/cycles/engine.py", line 134, in init
    user_path = os.path.dirname(os.path.abspath(bpy.utils.user_resource('CONFIG', '')))
TypeError: patched_function() takes 1 positional argument but 2 were given
Python: Traceback (most recent call last):
  File "[...]/Blender/blender-2.92.0-linux-x64/2.92/scripts/startup/bl_ui/space_userpref.py", line 1811, in draw
    bpy.utils.user_resource('SCRIPTS', "addons"),
TypeError: patched_function() takes 1 positional argument but 2 were given
```
